/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exploradorfinal.img;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mmart
 */
public class telasDesafiosSeis extends javax.swing.JFrame {

    /**
     * Creates new form telasDesafiosSeis
     */
    public telasDesafiosSeis() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                int x = JOptionPane.showConfirmDialog(null, "Você realmente deseja sair?", "AVISO", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(x == JOptionPane.YES_OPTION){
                    System.exit(0);
                }
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcoesDesCinco = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        labelHeader = new javax.swing.JLabel();
        btnInsPilares = new javax.swing.JRadioButton();
        btnInsFaces = new javax.swing.JRadioButton();
        btnInsComodo = new javax.swing.JRadioButton();
        btnInspec = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoRadial3 = new javax.swing.JTextArea();
        btnDica = new javax.swing.JButton();
        btnAltUm = new javax.swing.JButton();
        btnAltDois = new javax.swing.JButton();
        btnAltTres = new javax.swing.JButton();
        btnAltQuatro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("O cômodo em que você entra se destaca por estar completamente\nvazio, com exceção de pilares no centro e do portão na parede\noposta.\n\nCom base no que vê, você precisará informar a quantidade\nde combinações possíveis entre as faces dos pilares.");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 510, 130));

        labelHeader.setForeground(new java.awt.Color(255, 255, 255));
        labelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/labelMayans.png"))); // NOI18N
        labelHeader.setMaximumSize(new java.awt.Dimension(46, 16));
        labelHeader.setMinimumSize(new java.awt.Dimension(46, 16));
        labelHeader.setPreferredSize(new java.awt.Dimension(46, 16));
        getContentPane().add(labelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 500, 60));

        opcoesDesCinco.add(btnInsPilares);
        btnInsPilares.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnInsPilares.setForeground(new java.awt.Color(255, 255, 255));
        btnInsPilares.setText("Pilares");
        btnInsPilares.setActionCommand("insPilares");
        btnInsPilares.setContentAreaFilled(false);
        getContentPane().add(btnInsPilares, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        opcoesDesCinco.add(btnInsFaces);
        btnInsFaces.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnInsFaces.setForeground(new java.awt.Color(255, 255, 255));
        btnInsFaces.setText("Faces");
        btnInsFaces.setActionCommand("insFaces");
        btnInsFaces.setContentAreaFilled(false);
        btnInsFaces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsFacesActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsFaces, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        opcoesDesCinco.add(btnInsComodo);
        btnInsComodo.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnInsComodo.setForeground(new java.awt.Color(255, 255, 255));
        btnInsComodo.setText("Cômodo");
        btnInsComodo.setActionCommand("insComodo");
        btnInsComodo.setContentAreaFilled(false);
        getContentPane().add(btnInsComodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        btnInspec.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        btnInspec.setForeground(new java.awt.Color(255, 255, 255));
        btnInspec.setText("Inspecionar");
        btnInspec.setBorder(null);
        btnInspec.setContentAreaFilled(false);
        btnInspec.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInspec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInspecActionPerformed(evt);
            }
        });
        getContentPane().add(btnInspec, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 170, -1));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textoRadial3.setEditable(false);
        textoRadial3.setBackground(new java.awt.Color(0, 0, 0));
        textoRadial3.setColumns(20);
        textoRadial3.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textoRadial3.setForeground(new java.awt.Color(255, 255, 255));
        textoRadial3.setRows(5);
        jScrollPane2.setViewportView(textoRadial3);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 510, 110));

        btnDica.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnDica.setForeground(new java.awt.Color(255, 255, 255));
        btnDica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/maptinyIcon.png"))); // NOI18N
        btnDica.setText(" DICA");
        btnDica.setContentAreaFilled(false);
        btnDica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 140, 60));

        btnAltUm.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnAltUm.setForeground(new java.awt.Color(255, 255, 255));
        btnAltUm.setText("32");
        btnAltUm.setContentAreaFilled(false);
        btnAltUm.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAltUm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltUmMouseEntered(evt);
            }
        });
        btnAltUm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltUmActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltUm, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, 70, 50));

        btnAltDois.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnAltDois.setForeground(new java.awt.Color(255, 255, 255));
        btnAltDois.setText("648");
        btnAltDois.setContentAreaFilled(false);
        btnAltDois.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAltDois.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltDoisMouseEntered(evt);
            }
        });
        btnAltDois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltDoisActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltDois, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 80, 40));

        btnAltTres.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnAltTres.setForeground(new java.awt.Color(255, 255, 255));
        btnAltTres.setText("1024");
        btnAltTres.setContentAreaFilled(false);
        btnAltTres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAltTres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltTresMouseEntered(evt);
            }
        });
        btnAltTres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltTresActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltTres, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 520, 100, 40));

        btnAltQuatro.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        btnAltQuatro.setForeground(new java.awt.Color(255, 255, 255));
        btnAltQuatro.setText("1640");
        btnAltQuatro.setContentAreaFilled(false);
        btnAltQuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAltQuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAltQuatroMouseEntered(evt);
            }
        });
        btnAltQuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAltQuatroActionPerformed(evt);
            }
        });
        getContentPane().add(btnAltQuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 520, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/fundoIndiOptions.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsFacesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsFacesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsFacesActionPerformed

    private void btnInspecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInspecActionPerformed
        try {
            switch (opcoesDesCinco.getSelection().getActionCommand()) { // Pega a seleção do usuário no radial
                case "insPilares":
                textoRadial3.setText("São 6 pilares ao todo: 4 deles possuem 4 faces, e os"
                    + "\noutros possuem 2 faces. Além disso, você percebe"
                    + "\ninúmeros buracos no chão e se assombra ao perceber"
                    + "\no que significam. Você deve escolher com cuidado."); // Seta texto para pilares

                break;
                case "insFaces":
                textoRadial3.setText("As faces, você percebe, retratam deuses da cultura asteca."
                    + "\nSão eles: Tlaloc(deus da chuva), Chalchiutotolin(deus"
                    + "\ndas pragas e pestes), Quetzalcoatl(deus da vida) e "
                    + "\nTezcatlipoca(deus da morte). Os pilares com duas faces"
                    + "\nretratam apenas uma figura angelical e outra diabólica."); // Seta texto para faces
                //Seta texto para o papiro
                break;
                case "insComodo":
                textoRadial3.setText("Como você percebeu ao entrar, as paredes de blocos gastos "
                    + "\nestão nuas, com exceção de algumas correntes e sangue "
                    + "\nfresco nas paredes. Você deverá escrever a resposta com " // Seta texto para o cômodo
                    + "\nsangue na placa do pilar central.");
                break;
                default:
                JOptionPane.showMessageDialog(null, "Selecione algo para inspecionar.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Selecione algo para inspecionar.");
        }
    }//GEN-LAST:event_btnInspecActionPerformed

    private void btnDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDicaActionPerformed
        JOptionPane.showMessageDialog(null, "Utilize potenciação para este exercício.");
    }//GEN-LAST:event_btnDicaActionPerformed

    private void btnAltUmMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltUmMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltUmMouseEntered

    private void btnAltUmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltUmActionPerformed
        new telasFeedbackGameOver().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAltUmActionPerformed

    private void btnAltDoisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltDoisMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltDoisMouseEntered

    private void btnAltDoisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltDoisActionPerformed
        new telasFeedbackGameOver().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltDoisActionPerformed

    private void btnAltTresMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltTresMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltTresMouseEntered

    private void btnAltTresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltTresActionPerformed
        new telasLoreDois().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAltTresActionPerformed

    private void btnAltQuatroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAltQuatroMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAltQuatroMouseEntered

    private void btnAltQuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAltQuatroActionPerformed
        new telasFeedbackGameOver().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAltQuatroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosSeis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosSeis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosSeis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosSeis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telasDesafiosSeis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAltDois;
    private javax.swing.JButton btnAltQuatro;
    private javax.swing.JButton btnAltTres;
    private javax.swing.JButton btnAltUm;
    private javax.swing.JButton btnDica;
    private javax.swing.JRadioButton btnInsComodo;
    private javax.swing.JRadioButton btnInsFaces;
    private javax.swing.JRadioButton btnInsPilares;
    private javax.swing.JButton btnInspec;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelHeader;
    private javax.swing.ButtonGroup opcoesDesCinco;
    private javax.swing.JTextArea textoRadial3;
    // End of variables declaration//GEN-END:variables
}
