/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exploradorfinal.img;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mmart
 */
public class telasDesafiosTres extends javax.swing.JFrame {

    /**
     * Creates new form telasDesafiosTres
     */
    public telasDesafiosTres() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                int x = JOptionPane.showConfirmDialog(null, "Você realmente deseja sair?", "AVISO", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(x == JOptionPane.YES_OPTION){
                    System.exit(0);
                }
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoBase = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btnInsMesa = new javax.swing.JRadioButton();
        btnInsPapiro = new javax.swing.JRadioButton();
        btnInsCamara = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoRadial = new javax.swing.JTextArea();
        btnDica = new javax.swing.JButton();
        tFieldResposta = new javax.swing.JTextField();
        labelEnunciado = new javax.swing.JLabel();
        btnResposta = new javax.swing.JButton();
        labelHeader = new javax.swing.JLabel();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        textoBase.setEditable(false);
        textoBase.setBackground(new java.awt.Color(0, 0, 0));
        textoBase.setColumns(20);
        textoBase.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textoBase.setForeground(new java.awt.Color(255, 255, 255));
        textoBase.setRows(5);
        textoBase.setText("A câmara que você explora agora lembra os esgotos de sua\ncidade natal.\n\nA arquitetura ímpar do local contrasta com o cenário à \nsua frente: uma grande estátua de mármore, uma réplica quase\nperfeita da Justiça, jaz incólume sobre um pedestal.\nA balança que ela carrega pende para o lado direito, onde se\nencontra um ídolo de bronze. Moedas estão dispostas sobre uma\nmesa de madeira pútrida. Há também um papiro aberto.\n");
        textoBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoBase.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(textoBase);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 510, 220));

        jButton1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inspecionar");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 170, -1));

        buttonGroup1.add(btnInsMesa);
        btnInsMesa.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnInsMesa.setForeground(new java.awt.Color(255, 255, 255));
        btnInsMesa.setText("Mesa");
        btnInsMesa.setActionCommand("insMesa");
        btnInsMesa.setContentAreaFilled(false);
        getContentPane().add(btnInsMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        buttonGroup1.add(btnInsPapiro);
        btnInsPapiro.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnInsPapiro.setForeground(new java.awt.Color(255, 255, 255));
        btnInsPapiro.setText("Papiro");
        btnInsPapiro.setActionCommand("insPapiro");
        btnInsPapiro.setContentAreaFilled(false);
        getContentPane().add(btnInsPapiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        buttonGroup1.add(btnInsCamara);
        btnInsCamara.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnInsCamara.setForeground(new java.awt.Color(255, 255, 255));
        btnInsCamara.setText("Câmara");
        btnInsCamara.setActionCommand("insCamara");
        btnInsCamara.setContentAreaFilled(false);
        getContentPane().add(btnInsCamara, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, -1, -1));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textoRadial.setEditable(false);
        textoRadial.setBackground(new java.awt.Color(0, 0, 0));
        textoRadial.setColumns(20);
        textoRadial.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textoRadial.setForeground(new java.awt.Color(255, 255, 255));
        textoRadial.setRows(5);
        jScrollPane2.setViewportView(textoRadial);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 510, 110));

        btnDica.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnDica.setForeground(new java.awt.Color(255, 255, 255));
        btnDica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/maptinyIcon.png"))); // NOI18N
        btnDica.setText(" DICA");
        btnDica.setContentAreaFilled(false);
        btnDica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 140, 60));
        getContentPane().add(tFieldResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 270, -1));

        labelEnunciado.setFont(new java.awt.Font("Papyrus", 1, 13)); // NOI18N
        labelEnunciado.setForeground(new java.awt.Color(255, 255, 255));
        labelEnunciado.setText("Monte aqui a equação no seguinte padrão: (AX [+/-] B = C)");
        getContentPane().add(labelEnunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 510, -1, -1));

        btnResposta.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnResposta.setForeground(new java.awt.Color(255, 255, 255));
        btnResposta.setText("Responder");
        btnResposta.setBorder(null);
        btnResposta.setContentAreaFilled(false);
        btnResposta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespostaActionPerformed(evt);
            }
        });
        getContentPane().add(btnResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 540, 120, 30));

        labelHeader.setForeground(new java.awt.Color(255, 255, 255));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/justiceBanner.png"))); // NOI18N
        labelHeader.setMaximumSize(new java.awt.Dimension(46, 16));
        labelHeader.setMinimumSize(new java.awt.Dimension(46, 16));
        labelHeader.setPreferredSize(new java.awt.Dimension(46, 16));
        getContentPane().add(labelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 500, 60));

        labelFundo.setBackground(new java.awt.Color(0, 0, 0));
        labelFundo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/fundoIndi.png"))); // NOI18N
        getContentPane().add(labelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
        switch (buttonGroup1.getSelection().getActionCommand()) { // Pega a seleção do usuário no radial
            case "insMesa":
                textoRadial.setText("A mesa contém somente as moedas e o papiro. Você conta 30"
                                    + "\nmoedas."); // Seta texto para mesa
                break;
            case "insPapiro":
                textoRadial.setText("O papiro mostra a imagem do ídolo e o número 16. Também "
                                    + "\ndiz: 'O lado esquerdo vale três vezes menos cinco "
                                    + "\no direito.'");
                                    //Seta texto para o papiro
                break;
            case "insCamara":
                textoRadial.setText("Você passa os olhos pela câmara e percebe que a balança "
                                    + "\nestá diretamente ligada ao portão. "
                                    + "\nSomente resolvendo o enigma você poderá avançar. "); // Seta texto para a câmara
                break;
            default:
                JOptionPane.showMessageDialog(null, "Selecione algo para inspecionar."); // Caso não selecione nada, esta mensagem retorna
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Selecione algo para inspecionar."); // Evita que o console retorne um erro
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDicaActionPerformed
        JOptionPane.showMessageDialog(null, "Monte uma expressão algébrica usando o enunciado do papiro. Não é necessário resolver."); // Dica da fase
    }//GEN-LAST:event_btnDicaActionPerformed

    private void btnRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespostaActionPerformed

        if(tFieldResposta.getText().equals("3X - 5 = 16") || tFieldResposta.getText().equals("3x - 5 = 16")){ // Se a resposta for igual a isso, o retorno é positivo
            
            new telasFeedbackPositivo().setVisible(true);
            this.dispose();
        }
        else if(tFieldResposta.getText().equals("3X-5=16") || tFieldResposta.getText().equals("3x-5=16")){ // Aqui pede espaço
            JOptionPane.showMessageDialog(null, "Use espaços para separar os elementos como no exemplo.");
            tFieldResposta.setText("");
        }
        else if(tFieldResposta.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Digite uma resposta no campo ao lado."); // Se tiver em branco, pede para preencher
        }
        else{
            new telasFeedbackGameOver().setVisible(true); // Respostas erradas resultam em GameOver
            this.dispose();
        }
    }//GEN-LAST:event_btnRespostaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosTres.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                     new telasDesafiosTres().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDica;
    private javax.swing.JRadioButton btnInsCamara;
    private javax.swing.JRadioButton btnInsMesa;
    private javax.swing.JRadioButton btnInsPapiro;
    private javax.swing.JButton btnResposta;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelEnunciado;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JTextField tFieldResposta;
    private javax.swing.JTextArea textoBase;
    private javax.swing.JTextArea textoRadial;
    // End of variables declaration//GEN-END:variables
}
