/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exploradorfinal.img;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mmart
 */
public class telasDesafiosDois extends javax.swing.JFrame {

    /**
     * Creates new form telasDesafiosDois
     */
    public telasDesafiosDois() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                int x = JOptionPane.showConfirmDialog(null, "Você realmente deseja sair?", "AVISO", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(x == JOptionPane.YES_OPTION){
                    System.exit(0);
                }
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnDica = new javax.swing.JButton();
        labelHeader = new javax.swing.JLabel();
        btnRecI = new javax.swing.JButton();
        btnRecII = new javax.swing.JButton();
        btnRecIII = new javax.swing.JButton();
        btnAlt1 = new javax.swing.JButton();
        btnAlt2 = new javax.swing.JButton();
        btnAlt3 = new javax.swing.JButton();
        btnAlt4 = new javax.swing.JButton();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setToolTipText("");
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Ao adentrar esta câmara, um odor fétido invade suas narinas.\n\nSua estrutura segue o padrão da Masmorra visto até aqui: \nparedes desgastadas com a ação do tempo e uma constante\nsensação de claustrofobia.\nAqui, você vê três recipientes: os dois primeiros estão vazios\ne o terceiro está cheio de moedas, que você identifica serem\nFlorins de Eduardo III, cunhadas em 1343 na Inglaterra.\n\nUm saco repleto de florins está na frente dos dois recipientes\ne você entende que deve inserir moedas em ambos de forma a \nequivaler ao terceiro.\n\nQuantas moedas irão, respectivamente, no primeiro e segundo\nrecipientes?\n");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 510, 320));

        btnDica.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnDica.setForeground(new java.awt.Color(255, 255, 255));
        btnDica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/maptinyIcon.png"))); // NOI18N
        btnDica.setText(" DICA");
        btnDica.setContentAreaFilled(false);
        btnDica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 140, 60));

        labelHeader.setForeground(new java.awt.Color(255, 255, 255));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/coinsEdit.jpg"))); // NOI18N
        labelHeader.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        labelHeader.setMaximumSize(new java.awt.Dimension(46, 16));
        labelHeader.setMinimumSize(new java.awt.Dimension(46, 16));
        labelHeader.setPreferredSize(new java.awt.Dimension(46, 16));
        getContentPane().add(labelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 500, 60));

        btnRecI.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnRecI.setForeground(new java.awt.Color(255, 255, 255));
        btnRecI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/boxIcon.png"))); // NOI18N
        btnRecI.setText("Recipiente I");
        btnRecI.setContentAreaFilled(false);
        btnRecI.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecIActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecI, new org.netbeans.lib.awtextra.AbsoluteConstraints(306, 470, 180, 20));

        btnRecII.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnRecII.setForeground(new java.awt.Color(255, 255, 255));
        btnRecII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/boxIcon.png"))); // NOI18N
        btnRecII.setText("Recipiente II");
        btnRecII.setContentAreaFilled(false);
        btnRecII.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecIIActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecII, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 180, 20));

        btnRecIII.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnRecIII.setForeground(new java.awt.Color(255, 255, 255));
        btnRecIII.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/boxIcon.png"))); // NOI18N
        btnRecIII.setText("Recipiente III");
        btnRecIII.setContentAreaFilled(false);
        btnRecIII.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRecIII.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecIIIActionPerformed(evt);
            }
        });
        getContentPane().add(btnRecIII, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 550, 185, 20));

        btnAlt1.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        btnAlt1.setForeground(new java.awt.Color(255, 255, 255));
        btnAlt1.setText("450 / 150");
        btnAlt1.setContentAreaFilled(false);
        btnAlt1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlt1MouseEntered(evt);
            }
        });
        btnAlt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlt1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(53, 440, 120, 50));

        btnAlt2.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        btnAlt2.setForeground(new java.awt.Color(255, 255, 255));
        btnAlt2.setText("300 / 300");
        btnAlt2.setContentAreaFilled(false);
        btnAlt2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlt2MouseEntered(evt);
            }
        });
        btnAlt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlt2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 520, 120, 40));

        btnAlt3.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        btnAlt3.setForeground(new java.awt.Color(255, 255, 255));
        btnAlt3.setText("360 / 240");
        btnAlt3.setContentAreaFilled(false);
        btnAlt3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlt3MouseEntered(evt);
            }
        });
        btnAlt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlt3ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 450, 120, 40));

        btnAlt4.setFont(new java.awt.Font("Papyrus", 1, 16)); // NOI18N
        btnAlt4.setForeground(new java.awt.Color(255, 255, 255));
        btnAlt4.setText("320 / 280");
        btnAlt4.setContentAreaFilled(false);
        btnAlt4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAlt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlt4MouseEntered(evt);
            }
        });
        btnAlt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlt4ActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 520, 120, 40));

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/fundoIndiOptions.png"))); // NOI18N
        getContentPane().add(labelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDicaActionPerformed
        JOptionPane.showMessageDialog(null, "Você deve usar uma equação."); // Dica da fase
    }//GEN-LAST:event_btnDicaActionPerformed

    private void btnRecIIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecIIIActionPerformed
        JOptionPane.showMessageDialog(null, "O algarismo gravado diz: 600"); // Inspeciona o recipiente III
    }//GEN-LAST:event_btnRecIIIActionPerformed

    private void btnRecIIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecIIActionPerformed
        JOptionPane.showMessageDialog(null, "O algarismo gravado diz: 2X"); // Inspeciona o recipiente II
    }//GEN-LAST:event_btnRecIIActionPerformed

    private void btnRecIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecIActionPerformed
        JOptionPane.showMessageDialog(null, "O algarismo gravado diz: 3X"); // Inspeciona o recipiente I
    }//GEN-LAST:event_btnRecIActionPerformed

    private void btnAlt1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlt1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlt1MouseEntered

    private void btnAlt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlt1ActionPerformed
        new telasFeedbackGameOver().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlt1ActionPerformed

    private void btnAlt2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlt2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlt2MouseEntered

    private void btnAlt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlt2ActionPerformed
        new telasFeedbackGameOver().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlt2ActionPerformed

    private void btnAlt3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlt3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlt3MouseEntered

    private void btnAlt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlt3ActionPerformed
        new telasFeedbackPositivo().setVisible(true); // Encaminha para feedbackPositivo, onde haverá um novo sorteio
        this.dispose();       
    }//GEN-LAST:event_btnAlt3ActionPerformed

    private void btnAlt4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlt4MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlt4MouseEntered

    private void btnAlt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlt4ActionPerformed
        new telasFeedbackGameOver().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAlt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosDois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                  new telasDesafiosDois().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlt1;
    private javax.swing.JButton btnAlt2;
    private javax.swing.JButton btnAlt3;
    private javax.swing.JButton btnAlt4;
    private javax.swing.JButton btnDica;
    private javax.swing.JButton btnRecI;
    private javax.swing.JButton btnRecII;
    private javax.swing.JButton btnRecIII;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelHeader;
    // End of variables declaration//GEN-END:variables
}
