/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exploradorfinal.img;
import static exploradorfinal.img.classeRandom.defineFase;
import static exploradorfinal.img.classeRandom.recordaFases;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mmart
 */
public class telasIntroducao extends javax.swing.JFrame {

    /**
     * Creates new form telasIntroducao
     */
    public static ArrayList<Integer> histFases = new ArrayList<Integer>(); // Inicia a ArrayList que armazena as fases
    
    public telasIntroducao() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                int x = JOptionPane.showConfirmDialog(null, "Você realmente deseja sair?", "AVISO", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(x == JOptionPane.YES_OPTION){
                    System.exit(0);
                }
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnSair = new javax.swing.JButton();
        btnComecar = new javax.swing.JButton();
        btnSair1 = new javax.swing.JButton();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 600));
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        labelTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        labelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        labelTitulo.setText("INTRODUÇÃO");
        getContentPane().add(labelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea1.setRows(5);
        jTextArea1.setText("Olá, viajante!\n\nVocê está prestes a explorar um local de ruína e \nperdição: a Masmorra dos Segredos!\n\nAcredite, muitos tentaram antes de você.  \nTodos falharam.\nSerá que você é capaz de superar os desafios?\n\nBom, o que está esperando?\nVamos lá!");
        jTextArea1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextArea1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 510, 280));

        btnSair.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(255, 255, 255));
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/menu_icon-icons.com_69502.png"))); // NOI18N
        btnSair.setText("Menu");
        btnSair.setContentAreaFilled(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 120, 40));

        btnComecar.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        btnComecar.setForeground(new java.awt.Color(255, 255, 255));
        btnComecar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/forward-arrow_icon-icons.com_72749.png"))); // NOI18N
        btnComecar.setText(" Começar");
        btnComecar.setContentAreaFilled(false);
        btnComecar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComecar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComecarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComecar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, 50));

        btnSair1.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnSair1.setForeground(new java.awt.Color(255, 255, 255));
        btnSair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/signout_106525.png"))); // NOI18N
        btnSair1.setText("Sair");
        btnSair1.setContentAreaFilled(false);
        btnSair1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSair1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSair1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 540, 110, 40));

        labelFundo.setBackground(new java.awt.Color(0, 0, 0));
        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/fundoIndi.png"))); // NOI18N
        labelFundo.setText("jLabel1");
        labelFundo.setMaximumSize(new java.awt.Dimension(800, 600));
        labelFundo.setMinimumSize(new java.awt.Dimension(800, 600));
        labelFundo.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(labelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        new menuInicial().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnComecarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComecarActionPerformed
        int proxFase = defineFase(); // Chama a função defineFase() para escolher a próxima tela
        if(proxFase != 7){ 
        recordaFases(proxFase); // Se o retorno não for 7, ele armazena no ArrayList
        }
        switch(proxFase){ // Implementa o switch no retorno de defineFase()
            case 0:
                new telasDesafiosUm().setVisible(true);
                this.dispose();
                break;
            case 1:
                new telasDesafiosDois().setVisible(true);
                this.dispose();
                break;
            case 2:
                new telasDesafiosTres().setVisible(true);
                this.dispose();
                break;
            case 3:
                new telasDesafiosQuatro().setVisible(true);
                this.dispose();
                break;
            case 4:
                new telasDesafiosSeis().setVisible(true);
                this.dispose();
                break;
            case 7:
                new telasLoreTres().setVisible(true);
                this.dispose();
                break;
        }
    }//GEN-LAST:event_btnComecarActionPerformed

    private void btnSair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSair1ActionPerformed
        System.exit(0); // Sai do jogo
    }//GEN-LAST:event_btnSair1ActionPerformed
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telasIntroducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telasIntroducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telasIntroducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telasIntroducao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telasIntroducao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComecar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSair1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelTitulo;
    // End of variables declaration//GEN-END:variables
}
