/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package exploradorfinal.img;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author mmart
 */

public class telasDesafiosQuatro extends javax.swing.JFrame {

    /**
     * Creates new form telasDesafiosQuatro
     */
    
    public telasDesafiosQuatro() {
        initComponents();
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent we) {
                int x = JOptionPane.showConfirmDialog(null, "Você realmente deseja sair?", "AVISO", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                if(x == JOptionPane.YES_OPTION){
                    System.exit(0);
                }
            }
            
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        opcoesDesQuatro = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoBase = new javax.swing.JTextArea();
        btnInsAmbiente = new javax.swing.JRadioButton();
        btnInsMonolito = new javax.swing.JRadioButton();
        btnInsEsqueleto = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textoRadial2 = new javax.swing.JTextArea();
        btnDica = new javax.swing.JButton();
        cmbBoxMilhar = new javax.swing.JComboBox<>();
        cmbBoxCentena = new javax.swing.JComboBox<>();
        cmbBoxDezena = new javax.swing.JComboBox<>();
        cmbBoxUnidade = new javax.swing.JComboBox<>();
        btnResposta = new javax.swing.JButton();
        labelMonolito = new javax.swing.JLabel();
        labelHeader = new javax.swing.JLabel();
        labelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setBackground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setBorder(null);
        jScrollPane1.setToolTipText("");

        textoBase.setEditable(false);
        textoBase.setBackground(new java.awt.Color(0, 0, 0));
        textoBase.setColumns(20);
        textoBase.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textoBase.setForeground(new java.awt.Color(255, 255, 255));
        textoBase.setRows(5);
        textoBase.setText("A primeira coisa que você nota são os quadros inquietantes nas \nparedes. Uma longa mesa se estende desde a entrada da câmara até\no portão no outro lado da sala, repleta de jarros, pratos e taças\nempoeiradas, mas sem comida. \nAs cadeiras que pontuam o espaço estão ocupadas por esqueletos \npútridos, vestidos com trajes de diferentes épocas. \nNa ponta da mesa há um monolito de pedra, com cerca de um metro \nde altura e cinquenta centímetros de largura.\n\n");
        textoBase.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoBase.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(textoBase);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 530, 210));

        opcoesDesQuatro.add(btnInsAmbiente);
        btnInsAmbiente.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnInsAmbiente.setForeground(new java.awt.Color(255, 255, 255));
        btnInsAmbiente.setText("Ambiente");
        btnInsAmbiente.setActionCommand("insAmbiente");
        btnInsAmbiente.setContentAreaFilled(false);
        getContentPane().add(btnInsAmbiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        opcoesDesQuatro.add(btnInsMonolito);
        btnInsMonolito.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnInsMonolito.setForeground(new java.awt.Color(255, 255, 255));
        btnInsMonolito.setText("Monolito");
        btnInsMonolito.setActionCommand("insMonolito");
        btnInsMonolito.setContentAreaFilled(false);
        getContentPane().add(btnInsMonolito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, -1, -1));

        opcoesDesQuatro.add(btnInsEsqueleto);
        btnInsEsqueleto.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnInsEsqueleto.setForeground(new java.awt.Color(255, 255, 255));
        btnInsEsqueleto.setText("Esqueletos");
        btnInsEsqueleto.setActionCommand("insEsqueletos");
        btnInsEsqueleto.setContentAreaFilled(false);
        getContentPane().add(btnInsEsqueleto, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 340, -1, -1));

        jButton1.setFont(new java.awt.Font("Papyrus", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Inspecionar");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 340, 170, -1));

        jScrollPane2.setBorder(null);
        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setToolTipText("");
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        textoRadial2.setEditable(false);
        textoRadial2.setBackground(new java.awt.Color(0, 0, 0));
        textoRadial2.setColumns(20);
        textoRadial2.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        textoRadial2.setForeground(new java.awt.Color(255, 255, 255));
        textoRadial2.setRows(5);
        jScrollPane2.setViewportView(textoRadial2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, 510, 110));

        btnDica.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnDica.setForeground(new java.awt.Color(255, 255, 255));
        btnDica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/maptinyIcon.png"))); // NOI18N
        btnDica.setText(" DICA");
        btnDica.setContentAreaFilled(false);
        btnDica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDicaActionPerformed(evt);
            }
        });
        getContentPane().add(btnDica, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 520, 140, 60));

        cmbBoxMilhar.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        cmbBoxMilhar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmbBoxMilhar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxMilharActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBoxMilhar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 60, 40));

        cmbBoxCentena.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        cmbBoxCentena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmbBoxCentena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxCentenaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBoxCentena, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 540, 60, 40));

        cmbBoxDezena.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        cmbBoxDezena.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmbBoxDezena.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxDezenaActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBoxDezena, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 540, 60, 40));

        cmbBoxUnidade.setFont(new java.awt.Font("Papyrus", 1, 24)); // NOI18N
        cmbBoxUnidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9" }));
        cmbBoxUnidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxUnidadeActionPerformed(evt);
            }
        });
        getContentPane().add(cmbBoxUnidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 540, 60, 40));

        btnResposta.setFont(new java.awt.Font("Papyrus", 1, 14)); // NOI18N
        btnResposta.setForeground(new java.awt.Color(255, 255, 255));
        btnResposta.setText("Responder");
        btnResposta.setBorder(null);
        btnResposta.setContentAreaFilled(false);
        btnResposta.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRespostaActionPerformed(evt);
            }
        });
        getContentPane().add(btnResposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 120, 30));

        labelMonolito.setForeground(new java.awt.Color(255, 255, 255));
        labelMonolito.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/stoneTextureExt.png"))); // NOI18N
        labelMonolito.setText("jLabel1");
        getContentPane().add(labelMonolito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 300, 90));

        labelHeader.setForeground(new java.awt.Color(255, 255, 255));
        labelHeader.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelHeader.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/labelSkulls.png"))); // NOI18N
        labelHeader.setMaximumSize(new java.awt.Dimension(46, 16));
        labelHeader.setMinimumSize(new java.awt.Dimension(46, 16));
        labelHeader.setPreferredSize(new java.awt.Dimension(46, 16));
        getContentPane().add(labelHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 500, 60));

        labelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgGame/fundoIndi.png"))); // NOI18N
        getContentPane().add(labelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try{
            switch (opcoesDesQuatro.getSelection().getActionCommand()) { // Pega a seleção do usuário no radial
                case "insAmbiente":
                textoRadial2.setText("Você olha melhor para os quadros na parede e percebe que"
                                    + "\nas figuras retratadas tem uma aparência pálida e não possuem "
                                    + "\nolhos. As órbitas vazias te encaram como se pudessem ver sua"
                                    + "\nalma."); // Seta texto para o ambiente
                        
                break;
                case "insMonolito":
                textoRadial2.setText("O monolito de pedra possui quatro cubos na parte frontal, "
                                    + "\ncada um com algarismos que vão do 0 ao 9. A figura de uma "
                                    + "\ncaveira com ossos cruzados paira sobre os cubos.");
                //Seta texto para o monolito
                break;
                case "insEsqueletos":
                textoRadial2.setText("Você conta 6 cadeiras e sobre cada uma está sentado um "
                                    + "\nesqueleto. Vermes correm pelos ossos pútridos. "
                                    + "\nCuriosamente, você repara que dois dos esqueletos não" // Seta texto para os esqueletos
                                    + "\npossuem uma das costelas.");
                break;
                default:
                JOptionPane.showMessageDialog(null, "Selecione algo para inspecionar.");
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Selecione algo para inspecionar.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDicaActionPerformed
        JOptionPane.showMessageDialog(null, "Considere o corpo humano com 206 ossos. Você deve inserir a quantidade de ossos.");
    }//GEN-LAST:event_btnDicaActionPerformed

    private void cmbBoxCentenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxCentenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxCentenaActionPerformed

    private void cmbBoxDezenaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxDezenaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxDezenaActionPerformed

    private void cmbBoxUnidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxUnidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxUnidadeActionPerformed

    private void cmbBoxMilharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxMilharActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxMilharActionPerformed

    private void btnRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRespostaActionPerformed

        if(cmbBoxMilhar.getSelectedItem().equals("1") && cmbBoxCentena.getSelectedItem().equals("2") && cmbBoxDezena.getSelectedItem().equals("3") && cmbBoxUnidade.getSelectedItem().equals("4")){
            new telasLoreUm().setVisible(true);
            this.dispose(); // Pega a seleção do usuário em cada box. Se a resposta for 1234, retorna positivo.
        }
        else if(cmbBoxMilhar.getSelectedItem().equals("0") && cmbBoxCentena.getSelectedItem().equals("0") && cmbBoxDezena.getSelectedItem().equals("0") && cmbBoxUnidade.getSelectedItem().equals("0")){
            JOptionPane.showMessageDialog(null, "Insira a resposta usando as caixas ao lado, seguindo o padrão MCDU."); // Se estiver zerado, retorna essa mensagem
        }
        else{
            new telasFeedbackGameOver().setVisible(true);
            this.dispose(); // Respostas incorretas resultam em GameOver
        }
    }//GEN-LAST:event_btnRespostaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosQuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosQuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosQuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(telasDesafiosQuatro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new telasDesafiosQuatro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDica;
    private javax.swing.JRadioButton btnInsAmbiente;
    private javax.swing.JRadioButton btnInsEsqueleto;
    private javax.swing.JRadioButton btnInsMonolito;
    private javax.swing.JButton btnResposta;
    private javax.swing.JComboBox<String> cmbBoxCentena;
    private javax.swing.JComboBox<String> cmbBoxDezena;
    private javax.swing.JComboBox<String> cmbBoxMilhar;
    private javax.swing.JComboBox<String> cmbBoxUnidade;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelFundo;
    private javax.swing.JLabel labelHeader;
    private javax.swing.JLabel labelMonolito;
    private javax.swing.ButtonGroup opcoesDesQuatro;
    private javax.swing.JTextArea textoBase;
    private javax.swing.JTextArea textoRadial2;
    // End of variables declaration//GEN-END:variables
}
